### ISSUE TITLE
Why is there so much css in your program?

### ISSUE THREAD

**Issue by nahidhk** [AbrarZaved/Club_Management_System_By_Django#1]
![Screenshot from 2024-07-16 18-21-02](https://github.com/user-attachments/assets/4097d5b6-2b0e-47ff-abe5-141839ad38b2)

**Comment by AbrarZaved** [comment]
My downloaded frontend theme is to blame for this.

**Comment by AbrarZaved** [comment]
The material dashboard theme I downloaded contains at most twenty thousand
lines of CSS code, which is why CSS has a greater ratio than others.
